### ISSUE TITLE
baxter実機でroslaunchなどが正常に機能しない

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1182]
baxter@sheetaで```roslaunch jsk_2015_05_ baxter_apc baxer.launch```を行ったところ何も反応がなくCtrl-Cでキルしたところ以下のようなメッセージが出ました。
```
% roslaunch jsk_2015_05_baxter_apc baxter.launch 
^C... logging to /home/baxter/.ros/log/b461f8aa-efec-11e5-b6e3-8cdcd4282014/roslaunch-sheeta-4911.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/baxter/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://133.11.216.173:44956/

SUMMARY
========

CLEAR PARAMETERS
 * /baxter_servo_node/

PARAMETERS
 * /account_info: /var/lib/robot/ac...
 * /active_user/joint_state_subscribe: True
 * /active_user/launch_user_name: False
 * /active_user/motor_subscribe: True
 * /active_user/odom_subscribe: False
 * /active_user/position_diff_threshold: 0.01
 * /active_user/robot_name: Baxter
 * /baxter_joint_trajectory/goal_time: 0.1
 * /baxter_joint_trajectory/left_e0_goal: -1.0
 * /baxter_joint_trajectory/left_e0_trajectory: -1.0
 * /baxter_joint_trajectory/left_e1_goal: -1.0
 * /baxter_joint_trajectory/left_e1_trajectory: -1.0
 * /baxter_joint_trajectory/left_s0_goal: -1.0
 * /baxter_joint_trajectory/left_s0_trajectory: -1.0
 * /baxter_joint_trajectory/left_s1_goal: -1.0
 * /baxter_joint_trajectory/left_s1_trajectory: -1.0
 * /baxter_joint_trajectory/left_w0_goal: -1.0
 * /baxter_joint_trajectory/left_w0_trajectory: -1.0
 * /baxter_joint_trajectory/left_w1_goal: -1.0
 * /baxter_joint_trajectory/left_w1_trajectory: -1.0
 * /baxter_joint_trajectory/left_w2_goal: -1.0
 * /baxter_joint_trajectory/left_w2_trajectory: -1.0
 * /baxter_joint_trajectory/right_e0_goal: -1.0
 * /baxter_joint_trajectory/right_e0_trajectory: -1.0
 * /baxter_joint_trajectory/right_e1_goal: -1.0
 * /baxter_joint_trajectory/right_e1_trajectory: -1.0
 * /baxter_joint_trajectory/right_s0_goal: -1.0
 * /baxter_joint_trajectory/right_s0_trajectory: -1.0
 * /baxter_joint_trajectory/right_s1_goal: -1.0
 * /baxter_joint_trajectory/right_s1_trajectory: -1.0
 * /baxter_joint_trajectory/right_w0_goal: -1.0
 * /baxter_joint_trajectory/right_w0_trajectory: -1.0
 * /baxter_joint_trajectory/right_w1_goal: -1.0
 * /baxter_joint_trajectory/right_w1_trajectory: -1.0
 * /baxter_joint_trajectory/right_w2_goal: -1.0
 * /baxter_joint_trajectory/right_w2_trajectory: -1.0
 * /baxter_joint_trajectory/stopped_velocity_tolerance: -1.0
 * /image_saver/filename_format: /tmp/baxter_camer...
 * /image_saver/save_all_image: False
 * /interactive_adjust_kiva_pod/frame_id: /base
 * /interactive_adjust_kiva_pod/initial_orientation: [0.003, -0.032, -...
 * /interactive_adjust_kiva_pod/initial_x: 1.455
 * /interactive_adjust_kiva_pod/initial_y: -0.029
 * /interactive_adjust_kiva_pod/initial_z: 0.495
 * /interactive_adjust_kiva_pod/object_a: 0.2
 * /interactive_adjust_kiva_pod/object_b: 0.2
 * /interactive_adjust_kiva_pod/object_g: 0.0
 * /interactive_adjust_kiva_pod/object_r: 0.0
 * /interactive_adjust_kiva_pod/object_type: cube
 * /interactive_adjust_kiva_pod/object_x: 0.865
 * /interactive_adjust_kiva_pod/object_y: 0.865
 * /interactive_adjust_kiva_pod/object_z: 1.0
 * /interactive_adjust_kiva_pod/publish_tf: True
 * /interactive_adjust_kiva_pod/tf_frame: kiva_pod_base
 * /kiva_pod_description: <?xml version="1....
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosserial_node_0/baud: 115200
 * /rosserial_node_0/port: /dev/ttyUSB0
 * /rosserial_node_1/baud: 115200
 * /rosserial_node_1/port: /dev/ttyUSB1
 * /rosversion: 1.11.16
 * /tweet_image_mux/lazy: True
 * /tweet_image_saver/filename_format: /tmp/tweet_image.jpg
 * /tweet_image_saver/image_transport: raw
 * /tweet_image_saver/save_all_image: False

NODES
  /
    active_user (roseus/roseus)
    baxter_joint_trajectory (baxter_interface/joint_trajectory_action_server.py)
    baxter_servo_node (baxter_tools/enable_robot.py)
    head_joint_trajectory (baxter_interface/head_action_server.py)
    image_saver (image_view/image_saver)
    interactive_adjust_kiva_pod (jsk_interactive_marker/marker_6dof)
    kiva_pod_state_publisher (robot_state_publisher/robot_state_publisher)
    left_hand_camera_fixer (jsk_baxter_startup/camera_info_fixer.py)
    right_hand_camera_fixer (jsk_baxter_startup/camera_info_fixer.py)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rosserial_node_0 (rosserial_python/serial_node.py)
    rosserial_node_1 (rosserial_python/serial_node.py)
    sound_play (sound_play/soundplay_node.py)
    tweet (rostwitter/tweet.py)
    tweet_client_worktime (roseus/roseus)
    tweet_image_mux (topic_tools/mux)
    tweet_image_saver (image_view/image_saver)

ERROR: unable to contact ROS master at [http://baxter:11311]
```
他にも```rostopic list```などにも反応がありませんでした。sheetaを再起動してみましたが改善はしませんでした。どのようにすれば解決できるでしょうか。

**Comment by ban-masa** [comment]
```
[rosmaster.master][INFO] 2016-03-16 03:46:57,571: publisherUpdate[/tf] -> http://133.11.216.173:33311/
[rosmaster.threadpool][ERROR] 2016-03-16 03:46:57,571: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/master_api.py", line 208, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

[rosmaster.master][INFO] 2016-03-16 03:46:57,571: publisherUpdate[/tf] -> http://133.11.216.173:53685/
[rosmaster.master][INFO] 2016-03-16 03:46:57,572: publisherUpdate[/tf] -> http://133.11.216.173:54242/
[rosmaster.master][INFO] 2016-03-16 03:46:57,573: publisherUpdate[/tf] -> http://133.11.216.173:40210/
[rosmaster.threadpool][ERROR] 2016-03-16 03:46:57,574: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/master_api.py", line 208, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 24] Too many open files

```

**Comment by ban-masa** [comment]
c.f. https://github.com/ros/ros_comm/issues/610

**Comment by ban-masa** [comment]
```
ruser@011310P0014 ~ $ uptime
 02:37:40 up 9 days, 21:12,  1 user,  load average: 2.35, 2.10, 2.06
ruser@011310P0014 ~ $ sudo reboot

```
で解決するかな。

**Comment by ban-masa** [comment]
とりあえずマスターは動きました
