### ISSUE TITLE
Test with rospack is not stable

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1256]
```
[jsk_apc2016_common] ====================================================================== 

[jsk_apc2016_common] ERROR: jsk_apc2016_common.tests.test_visualize_stow_json   

[jsk_apc2016_common] ---------------------------------------------------------------------- 

[jsk_apc2016_common] Traceback (most recent call last):                         

[jsk_apc2016_common]   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest 

[jsk_apc2016_common]     self.test(*self.arg)                                   

[jsk_apc2016_common]   File "/workspace/ros/ws_jsk_apc/src/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/tests/__init__.py", line 44, in test_visualize_stow_json 

[jsk_apc2016_common]     img = jsk_apc2016_common.visualize_stow_json(json_file) 

[jsk_apc2016_common]   File "/workspace/ros/ws_jsk_apc/src/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/__init__.py", line 101, in visualize_stow_json 

[jsk_apc2016_common]     kiva_pod_img = jsk_apc2015_common.visualize_bin_contents(bin_contents) 

[jsk_apc2016_common]   File "", line 70, in visualize_bin_contents      

[jsk_apc2016_common]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 200, in get_path 

[jsk_apc2016_common]     raise ResourceNotFound(name, ros_paths=self._ros_paths) 

[jsk_apc2016_common] ResourceNotFound: jsk_apc2015_common   
```

**Comment by wkentaro** [comment]
Recently it is stable, so closing now.
