### ISSUE TITLE
[jsk_2016_01_baxter_apc] rbo callback error with SoftKinetic Camera

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1421]
@yuyu2172 now #1410 is fixed, and i tried to use softkinetic on both arm, but i got these errors.

```
[INFO] [WallTime: 1462887464.394961] started
[INFO] [WallTime: 1462887465.471998] get_spatial elapsed time 0.999156951904
[ERROR] [WallTime: 1462887465.559949] bad callback: <bound method RBOSegmentationInBinNode._callback of <__main__.RBOSegmentationInBinNode object at 0x7f8308afb1d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py", line 85, in _callback
    self.segmentation()
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apcIndexError: index 299 is out of bounds for axis 1 with size 1542016_common/segmentation_in_bin/rbo_segmentation_in_bin.py", line 57, in segmentation
    desired_object=self.target_object)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 603, in predict
    self.backproject()
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 563, in backproject
    self.likelihood_images[feature_name][object_name][self.bin_mask] = Utils.backproject(self.likelihoods[feature_name][object_name], self.feature_images[feature_name][self.bin_mask])
IndexError: index 299 is out of bounds for axis 1 with size 154
```k_apc2016_common/segmentation_in_bin/rbo_segmentation_in_bin.py", line 57, in segmentation
    desired_object=self.target_object)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 603, in predict
    self.backproject()
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 563, in backproject
    self.likelihood_images[feature_name][object_name][self.bin_mask] = Utils.backproject(self.likelihoods[feature_name][object_name], self.feature_images[feature_name][self.bin_mask])
IndexError: index 299 is out of bounds for axis 1 with size 154
```

i thought it's because of size difference between point cloud and rgb image, so i resize rgb image color to same size as point cloud.
however, i got same error, but the last line is different as below.

```
IndexError: index 217 is out of bounds for axis 0 with size 217
```

**Comment by knorth55** [comment]
@yuyu2172 do you have any idea?

**Comment by yuyu2172** [comment]
@knorth55 
The error message says that you are accessing 218th value of some axis of a numpy array even though the size in the axis is 217.
Are you sure that sizes are same?

**Comment by knorth55** [comment]
@yuyu2172 i resized it, and i had same error. it's written in the previous comment.

**Comment by knorth55** [comment]
you can reproduce this error with commands below.
```bash
$ roslaunch jsk_2016_01_baxter_apc baxter.launch
$ roslaunch jsk_2016_01_baxter_apc setup_softkinetic.launch
$ roslaunch jsk_2016_01_baxter_apc segmentation_in_bin.launch json:=$(rospack find jsk_2015_05_baxter_apc) /json/layout_12.json
```

**Comment by wkentaro** [comment]
@yuyu2172 Is that possible for you to complete this by this Saturday?

**Comment by knorth55** [comment]
@yuyu2172 
upper: rgb image color shape
lower: mask color shape

```
[INFO] [WallTime: 1463062655.533600] started
[INFO] [WallTime: 1463062656.655322] get_spatial elapsed time 0.991035938263
(467, 469)
(572, 648)
/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py:565: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 467 but corresponding boolean dimension is 572
  self.likelihood_images[feature_name][object_name][self.bin_mask] = Utils.backproject(self.likelihoods[feature_name][object_name], self.feature_images[feature_name][self.bin_mask])
[ERROR] [WallTime: 1463062656.733234] bad callback: <bound method RBOSegmentationInBinNode._callback of <__main__.RBOSegmentationInBinNode object at 0x7ff66a8dc210>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py", line 85, in _callback
    self.segmentation()
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/segmentation_in_bin/rbo_segmentation_in_bin.py", line 57, in segmentation
    desired_object=self.target_object)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 605, in predict
    self.backproject()
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_apc2016_common/python/jsk_apc2016_common/rbo_segmentation/probabilistic_segmentation.py", line 565, in backproject
    self.likelihood_images[feature_name][object_name][self.bin_mask] = Utils.backproject(self.likelihoods[feature_name][object_name], self.feature_images[feature_name][self.bin_mask])
IndexError: index 467 is out of bounds for axis 0 with size 467
```

**Comment by knorth55** [comment]
@yuyu2172 did you find any good suggestion?

**Comment by yuyu2172** [comment]
There is no progress. I will work on it today.
