### ISSUE TITLE
Error occurs in rosdep install

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1527]
I faced the following error in rosdep install.
```
executing command [sudo -H pip install -U scikit-image]
Downloading/unpacking scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
  Running setup.py (path:/tmp/pip_build_root/scikit-image/setup.py) egg_info for package scikit-image
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    Unable to find pgen, not compiling formal grammar.
    
    Installed /tmp/pip_build_root/scikit-image/.eggs/Cython-0.24-py2.7-linux-x86_64.egg
    Partial import of skimage during the build process.
    build_src
    building extension "skimage._shared.geometry" sources
    building extension "skimage._shared.transform" sources
    building extension "skimage._shared.interpolation" sources
    building extension "skimage.draw._draw" sources
    building extension "skimage.feature.corner_cy" sources
    building extension "skimage.feature.censure_cy" sources
    building extension "skimage.feature.orb_cy" sources
    building extension "skimage.feature.brief_cy" sources
    building extension "skimage.feature._texture" sources
    building extension "skimage.feature._hessian_det_appx" sources
    building extension "skimage.feature._hoghistogram" sources
    building extension "skimage.restoration._unwrap_1d" sources
    building extension "skimage.restoration._unwrap_2d" sources
    building extension "skimage.restoration._unwrap_3d" sources
    building extension "skimage.restoration._denoise_cy" sources
    building extension "skimage.restoration._nl_means_denoising" sources
    building extension "skimage.filters._ctmf" sources
    building extension "skimage.filters.rank.core_cy" sources
    building extension "skimage.filters.rank.generic_cy" sources
    building extension "skimage.filters.rank.percentile_cy" sources
    building extension "skimage.filters.rank.bilateral_cy" sources
    building extension "skimage.future.graph._ncut_cy" sources
    building extension "skimage.graph._spath" sources
    building extension "skimage.graph._mcp" sources
    building extension "skimage.graph.heap" sources
    building extension "skimage.io._plugins._colormixer" sources
    building extension "skimage.io._plugins._histograms" sources
    building extension "skimage.measure._ccomp" sources
    building extension "skimage.measure._find_contours_cy" sources
    building extension "skimage.measure._moments_cy" sources
    building extension "skimage.measure._marching_cubes_cy" sources
    building extension "skimage.measure._pnpoly" sources
    building extension "skimage.morphology._watershed" sources
    building extension "skimage.morphology._skeletonize_cy" sources
    building extension "skimage.morphology._convex_hull" sources
    building extension "skimage.morphology._greyreconstruct" sources
    building extension "skimage.morphology._skeletonize_3d_cy" sources
    building extension "skimage.transform._hough_transform" sources
    building extension "skimage.transform._warps_cy" sources
    building extension "skimage.transform._radon_transform" sources
    building extension "skimage.transform._seam_carving" sources
    building extension "skimage.segmentation._felzenszwalb_cy" sources
    building extension "skimage.segmentation._quickshift" sources
    building extension "skimage.segmentation._slic" sources
    building extension "skimage.external.tifffile._tifffile" sources
    building data_files sources
    build_src: building npy-pkg config files
    
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/gh-pages'
Requirement already up-to-date: six>=1.7.3 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Downloading/unpacking networkx>=1.8 (from scikit-image)
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking pillow>=2.1.0 from https://pypi.python.org/packages/9a/88/3096061654487bcfcc1ccbe16b29ea669f783c01d3fbaac5813b920c3752/Pillow-3.2.0.zip#md5=a646213ed7bbbc020299af70782f368c (from scikit-image)
  Downloading Pillow-3.2.0.zip (10.5MB): 10.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pillow/setup.py) egg_info for package pillow
    
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking dask[array]>=0.5.0 (from scikit-image)
  Downloading dask-0.9.0-py2.py3-none-any.whl (203kB): 203kB downloaded
Downloading/unpacking decorator>=3.4.0 from https://pypi.python.org/packages/7d/ca/493b2377bf42d57bdd985c31975be3d2b500ad9079199cecb7633e8e2cde/decorator-4.0.9-py2.py3-none-any.whl#md5=8bb72dc6e496c3f748d7aeabe4bfe4ff (from networkx>=1.8->scikit-image)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Requirement already up-to-date: numpy; extra == "array" in /usr/local/lib/python2.7/dist-packages (from dask[array]>=0.5.0->scikit-image)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /root/.pip/pip.log
ERROR: the following rosdeps failed to install
  pip: command [sudo -H pip install -U scikit-image] failed
  pip: Failed to detect successful installation of [scikit-image]
```

**Comment by knorth55** [comment]
can you try `sudo -H pip install -U scikit-image` and check if you get same error?

**Comment by pazeshun** [comment]
```
$ sudo -H pip install -U scikit-image
[sudo] password for pazeshun: 
Downloading/unpacking scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
  Running setup.py (path:/tmp/pip_build_root/scikit-image/setup.py) egg_info for package scikit-image
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    Unable to find pgen, not compiling formal grammar.
    
    Installed /tmp/pip_build_root/scikit-image/.eggs/Cython-0.24-py2.7-linux-x86_64.egg
    Partial import of skimage during the build process.
    build_src
    building extension "skimage._shared.geometry" sources
    building extension "skimage._shared.transform" sources
    building extension "skimage._shared.interpolation" sources
    building extension "skimage.draw._draw" sources
    building extension "skimage.feature.corner_cy" sources
    building extension "skimage.feature.censure_cy" sources
    building extension "skimage.feature.orb_cy" sources
    building extension "skimage.feature.brief_cy" sources
    building extension "skimage.feature._texture" sources
    building extension "skimage.feature._hessian_det_appx" sources
    building extension "skimage.feature._hoghistogram" sources
    building extension "skimage.restoration._unwrap_1d" sources
    building extension "skimage.restoration._unwrap_2d" sources
    building extension "skimage.restoration._unwrap_3d" sources
    building extension "skimage.restoration._denoise_cy" sources
    building extension "skimage.restoration._nl_means_denoising" sources
    building extension "skimage.filters._ctmf" sources
    building extension "skimage.filters.rank.core_cy" sources
    building extension "skimage.filters.rank.generic_cy" sources
    building extension "skimage.filters.rank.percentile_cy" sources
    building extension "skimage.filters.rank.bilateral_cy" sources
    building extension "skimage.future.graph._ncut_cy" sources
    building extension "skimage.graph._spath" sources
    building extension "skimage.graph._mcp" sources
    building extension "skimage.graph.heap" sources
    building extension "skimage.io._plugins._colormixer" sources
    building extension "skimage.io._plugins._histograms" sources
    building extension "skimage.measure._ccomp" sources
    building extension "skimage.measure._find_contours_cy" sources
    building extension "skimage.measure._moments_cy" sources
    building extension "skimage.measure._marching_cubes_cy" sources
    building extension "skimage.measure._pnpoly" sources
    building extension "skimage.morphology._watershed" sources
    building extension "skimage.morphology._skeletonize_cy" sources
    building extension "skimage.morphology._convex_hull" sources
    building extension "skimage.morphology._greyreconstruct" sources
    building extension "skimage.morphology._skeletonize_3d_cy" sources
    building extension "skimage.transform._hough_transform" sources
    building extension "skimage.transform._warps_cy" sources
    building extension "skimage.transform._radon_transform" sources
    building extension "skimage.transform._seam_carving" sources
    building extension "skimage.segmentation._felzenszwalb_cy" sources
    building extension "skimage.segmentation._quickshift" sources
    building extension "skimage.segmentation._slic" sources
    building extension "skimage.external.tifffile._tifffile" sources
    building data_files sources
    build_src: building npy-pkg config files
    
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/gh-pages'
Requirement already up-to-date: six>=1.7.3 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Downloading/unpacking networkx>=1.8 (from scikit-image)
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking pillow>=2.1.0 from https://pypi.python.org/packages/9a/88/3096061654487bcfcc1ccbe16b29ea669f783c01d3fbaac5813b920c3752/Pillow-3.2.0.zip#md5=a646213ed7bbbc020299af70782f368c (from scikit-image)
  Downloading Pillow-3.2.0.zip (10.5MB): 10.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pillow/setup.py) egg_info for package pillow
    
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking dask[array]>=0.5.0 (from scikit-image)
  Downloading dask-0.9.0-py2.py3-none-any.whl (203kB): 203kB downloaded
Downloading/unpacking decorator>=3.4.0 from https://pypi.python.org/packages/7d/ca/493b2377bf42d57bdd985c31975be3d2b500ad9079199cecb7633e8e2cde/decorator-4.0.9-py2.py3-none-any.whl#md5=8bb72dc6e496c3f748d7aeabe4bfe4ff (from networkx>=1.8->scikit-image)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Requirement already up-to-date: numpy; extra == "array" in /usr/local/lib/python2.7/dist-packages (from dask[array]>=0.5.0->scikit-image)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /root/.pip/pip.log
```
I think the same error occurs.

**Comment by pazeshun** [comment]
In this environment,
```
$ pip show setuptools
Name: setuptools
Version: 21.2.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```
But I get the same error when I downgraded setuptools by `sudo pip install -U 'setuptools==20.7.0'`

**Comment by knorth55** [comment]
this error is caused by pip.
try `sudo pip install pip --upgrade` and the same command.

**Comment by pazeshun** [comment]
```
$ sudo pip install pip --upgrade
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
$ rosdep install -y -r --from-paths .
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
jsk_pr2_calibration: Cannot locate rosdep definition for [pr2_calibration_launch]
kinect2_bridge: Cannot locate rosdep definition for [kinect2_registration]
euscollada: Cannot locate rosdep definition for [urdfdom]
jsk_baxter_web: Cannot locate rosdep definition for [ros3djs]
kinect2_viewer: Cannot locate rosdep definition for [kinect2_bridge]
kinect2_calibration: Cannot locate rosdep definition for [kinect2_bridge]
jsk_pr2_startup: Cannot locate rosdep definition for [jsk_smart_gui]
jsk_tools: No definition of [rosemacs-el] for OS version [trusty]
Continuing to install resolvable dependencies...
executing command [sudo -H pip install -U scikit-image]
Collecting scikit-image
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading scikit_image-0.12.3-cp27-cp27mu-manylinux1_x86_64.whl (28.0MB)
    100% |████████████████████████████████| 28.0MB 51kB/s 
Collecting dask[array]>=0.5.0 (from scikit-image)
  Downloading dask-0.9.0-py2.py3-none-any.whl (203kB)
    100% |████████████████████████████████| 204kB 7.3MB/s 
Requirement already up-to-date: six>=1.7.3 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Collecting networkx>=1.8 (from scikit-image)
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 815kB/s 
Collecting pillow>=2.1.0 (from scikit-image)
  Downloading Pillow-3.2.0.zip (10.5MB)
    100% |████████████████████████████████| 10.5MB 137kB/s 
Requirement already up-to-date: numpy; extra == "array" in /usr/local/lib/python2.7/dist-packages (from dask[array]>=0.5.0->scikit-image)
Collecting toolz>=0.7.2; extra == "array" (from dask[array]>=0.5.0->scikit-image)
  Downloading toolz-0.7.4.tar.gz
Collecting decorator>=3.4.0 (from networkx>=1.8->scikit-image)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Building wheels for collected packages: pillow, toolz
  Running setup.py bdist_wheel for pillow ... done
  Stored in directory: /root/.cache/pip/wheels/88/2d/ce/3ff4ae4e2b8600d1bde1cbde5dfcc6d8770222c38348fe9139
  Running setup.py bdist_wheel for toolz ... done
  Stored in directory: /root/.cache/pip/wheels/3e/e9/72/b9e24c6b4c0347670b9a20afeba6b2534655f5dc714b30cb4e
Successfully built pillow toolz
Installing collected packages: toolz, dask, decorator, networkx, pillow, scikit-image
  Found existing installation: decorator 3.4.0
    Uninstalling decorator-3.4.0:
      Successfully uninstalled decorator-3.4.0
  Found existing installation: Pillow 2.3.0
    Uninstalling Pillow-2.3.0:
      Successfully uninstalled Pillow-2.3.0
Successfully installed dask-0.9.0 decorator-4.0.9 networkx-1.11 pillow-3.2.0 scikit-image-0.12.3 toolz-0.7.4
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
#All required rosdeps installed successfully
```
Error is resolved. @knorth55 Thank you.

**Comment by pazeshun** [comment]
After `$ sudo apt-get install python-pip`,
```
$ pip show pip
---
Name: pip
Version: 1.5.4
Location: /usr/lib/python2.7/dist-packages
Requires: 
```
And after `sudo pip install pip --upgrade`,
```
$ pip show pip
---
Metadata-Version: 2.0
Name: pip
Version: 8.1.2
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Build Tools
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: Implementation :: PyPy
Entry-points:
  [console_scripts]
  pip = pip:main
  pip3 = pip:main
  pip3.5 = pip:main
```
I think we must do `sudo pip install pip --upgrade` now.
Should we make doc about this?

**Comment by knorth55** [comment]
installing pip via apt is not recommended in pip doc. https://pip.pypa.io/en/stable/installing/
you do not need to write about it.

**Comment by pazeshun** [comment]
Ok, thank you for your information.
