### ISSUE TITLE
setup_torso sometimes raises error

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1756]
`setup_torso.launch` sometimes raise the following error:
```
[Info] [DepthPacketStreamParser] 4 packets were lost
[ERROR] [WallTime: 1466384407.743979] bad callback: <bound method VGG16ObjectRecognition._recognize of <__main__.VGG16ObjectRecognition object at 0x7fbfb3771cd0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/baxter/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/node_scripts/vgg16_object_recognition.py", line 55, in _recognize
    bgr = skimage.transform.resize(bgr, (224, 224), preserve_range=True)
TypeError: resize() got an unexpected keyword argument 'preserve_range'
```

**Comment by wkentaro** [comment]
This maybe caused by old scikit-image. Please upgrade scikit-image by 
```
sudo pip install scikit-image
```
