### ISSUE TITLE
baxter.launch raises error in demo env

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1908]
```
% roslaunch jsk_2016_01_baxter_apc baxter.launch 
... logging to /home/baxter/.ros/log/c2422d40-9236-11e6-ac88-000af716d1cb/roslaunch-sheeta-94863.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 682, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 625, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 662, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 256, in _param_tag
    vals = self.opt_attrs(tag, context, ('value', 'textfile', 'binfile', 'command'))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 202, in opt_attrs
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 325, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 141, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 184, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 200, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: jsk_apc2015_common
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_pr2_robot/jsk_pr2_calibration
ROS path [2]=/home/baxter/ros/jsk_apc_ws/src/FOR_PCL1.8/perception_pcl/pointcloud_to_laserscan
ROS path [3]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_naoqi_robot/jsk_nao_startup
ROS path [4]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_data
ROS path [5]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_tilt_laser
ROS path [6]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_baxter_robot/jsk_baxter_web
ROS path [7]=/home/baxter/ros/jsk_apc_ws/src/FOR_PCL1.8/perception_pcl/pcl_ros
ROS path [8]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/jsk_recognition
ROS path [9]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_fetch_robot/jsk_fetch_startup
ROS path [10]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_naoqi_robot/jsk_pepper_startup
ROS path [11]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/virtual_force_publisher
ROS path [12]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_coordination_system/dynamic_tf_publisher
ROS path [13]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/checkerboard_detector
ROS path [14]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_robot_common/jsk_robot_utils
ROS path [15]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_robot_common/roseus_remote
ROS path [16]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_naoqi_robot/naoeus
ROS path [17]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_topic_tools
ROS path [18]=/home/baxter/ros/jsk_apc_ws/src/FOR_PCL1.8/octomap_mapping/octomap_server
ROS path [19]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_ros_patch/image_view2
ROS path [20]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_naoqi_robot/peppereus
ROS path [21]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_baxter_robot/jsk_baxter_startup
ROS path [22]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_common/jsk_ros_patch/multi_map_server
ROS path [23]=/home/baxter/ros/jsk_apc_ws/src/start-jsk/jsk_apc/jsk_2015_05_baxter_apc
ROS path [24]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/jsk_recognition_utils
ROS path [25]=/home/baxter/ros/jsk_apc_ws/src/start-jsk/jsk_apc/jsk_apc2016_common
ROS path [26]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_naoqi_robot/jsk_201504_miraikan
ROS path [27]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_baxter_robot/jsk_baxter_desktop
ROS path [28]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros_utils
ROS path [29]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception
ROS path [30]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/imagesift
ROS path [31]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros
ROS path [32]=/home/baxter/ros/jsk_apc_ws/src/jsk-ros-pkg/jsk_recognition/resized_image_transport
ROS path [33]=/home/baxter/ros/jsk_apc_ws/src/FOR_LATEST_BAXTEREUS/jsk_robot/jsk_pr2_robot/jsk_pr2_startup
ROS path [34]=/home/baxter/ros/jsk_apc_ws/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc
ROS path [35]=/opt/ros/indigo/share
ROS path [36]=/opt/ros/indigo/stacks
```

**Comment by pazeshun** [comment]
Yesterday, I didn't face this error.

**Comment by pazeshun** [comment]
I rebuilt `jsk_apc_ws` and this was fixed.
