### ISSUE TITLE
Build failed in Jenkins: Ibin_uT64__jsk_arc2017_baxter__ubuntu_trusty_amd64__binary

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2598]
```
See <http://build.ros.org/job/Ibin_uT64__jsk_arc2017_baxter__ubuntu_trusty_amd64__binary/9/display/redirect>

------------------------------------------
[...truncated 766.15 KB...]
Setting up libpcl-apps-1.7-dev (1.7.1-3+trusty3) ...
Setting up libpcl-outofcore-1.7-dev (1.7.1-3+trusty3) ...
Setting up libpcl-people-1.7-dev (1.7.1-3+trusty3) ...
Setting up libpcl-1.7-all-dev (1.7.1-3+trusty3) ...
Setting up libpcl-1.7-all (1.7.1-3+trusty3) ...
Setting up libpyside-dev (1.2.1-4build1) ...
Setting up libqt4-opengl-dev (4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1) ...
Setting up libqtwebkit-dev (2.3.2-0ubuntu7) ...
Setting up libqwt-dev (6.0.0-1.2) ...
Setting up python-pyside.qtdeclarative (1.2.1-4build1) ...
Setting up python-pyside (1.2.1-4build1) ...
Setting up python-qt4 (4.10.4+dfsg-1ubuntu1) ...
Setting up python-qwt5-qt4 (5.2.1~cvs20091107+dfsg-7build1) ...
Setting up ros-indigo-baxter-sim-io (1.2.12-0trusty-20170313-085849-0700) ...
Setting up ros-indigo-pcl-conversions (0.2.1-0trusty-20170313-090426-0700) ...
Setting up ros-indigo-pcl-ros (1.2.7-0trusty-20170728-011511-0800) ...
Setting up ros-indigo-image-view2 (2.2.5-0trusty-20170728-013653-0800) ...
Setting up ros-indigo-jsk-recognition-utils (1.2.2-0trusty-20170728-031920-0800) ...
Setting up ros-indigo-imagesift (1.2.2-0trusty-20170728-044832-0800) ...
Setting up ros-indigo-python-qt-binding (0.2.19-0trusty-20170313-130449-0700) ...
Setting up ros-indigo-rviz (1.11.18-0trusty-20170821-143344-0800) ...
Setting up ros-indigo-jsk-rviz-plugins (2.1.2-0trusty-20170821-154534-0800) ...
Setting up ros-indigo-jsk-maps (0.0.4-0trusty-20170821-162039-0800) ...
Setting up ros-indigo-qt-gui (0.2.32-0trusty-20170313-131211-0700) ...
Setting up ros-indigo-rqt-gui (0.4.8-0trusty-20170428-095436-0800) ...
Setting up ros-indigo-rqt-gui-py (0.4.8-0trusty-20170428-101736-0800) ...
Setting up ros-indigo-rqt-bag (0.4.8-0trusty-20170428-110710-0800) ...
Setting up ros-indigo-jsk-data (2.2.5-0trusty-20170821-153512-0800) ...
Setting up ros-indigo-qt-gui-py-common (0.2.32-0trusty-20170313-131245-0700) ...
Setting up ros-indigo-qt-gui-cpp (0.2.32-0trusty-20170406-182029-0800) ...
Setting up ros-indigo-rqt-gui-cpp (0.4.8-0trusty-20170428-094745-0800) ...
Setting up ros-indigo-rqt-image-view (0.4.9-0trusty-20170907-155827-0800) ...
Setting up ros-indigo-qwt-dependency (1.0.1-0trusty-20160604-055232-0700) ...
Setting up ros-indigo-rqt-py-common (0.4.8-0trusty-20170428-095110-0800) ...
Setting up ros-indigo-rqt-plot (0.4.8-0trusty-20170428-105109-0800) ...
Setting up ros-indigo-jsk-rqt-plugins (2.1.2-0trusty-20170907-161636-0800) ...
Setting up ros-indigo-robot-self-filter (0.1.30-1trusty-20170814-095824-0800) ...
Setting up ros-indigo-jsk-perception (1.2.2-0trusty-20170907-224608-0800) ...
Setting up ros-indigo-pr2-navigation-self-filter (0.1.27-0trusty-20170814-095548-0800) ...
Setting up ros-indigo-jsk-demo-common (0.0.4-0trusty-20170915-160147-0800) ...
Setting up ros-indigo-jsk-apc2015-common (4.1.4-0trusty-20171015-074319-0800) ...
Setting up ros-indigo-octomap-server (0.6.0-0trusty-20170728-033108-0800) ...
Setting up ros-indigo-jsk-pcl-ros-utils (1.2.2-0trusty-20170915-173719-0800) ...
Setting up ros-indigo-jsk-pcl-ros (1.2.2-0trusty-20170915-184142-0800) ...
Setting up ros-indigo-jsk-2015-05-baxter-apc (4.1.4-0trusty-20171015-080635-0800) ...
Setting up ros-indigo-jsk-apc2016-common (4.1.4-0trusty-20171015-074255-0800) ...
Setting up ros-indigo-jsk-interactive-marker (2.1.2-0trusty-20170907-224625-0800) ...
Setting up ros-indigo-jsk-2016-01-baxter-apc (4.1.4-0trusty-20171015-081405-0800) ...
Setting up ros-indigo-rqt-logger-level (0.4.8-0trusty-20170428-110347-0800) ...
Setting up ros-indigo-rqt-console (0.4.8-0trusty-20170428-110936-0800) ...
Setting up ros-indigo-rqt-reconfigure (0.4.8-0trusty-20170428-123104-0800) ...
Setting up ros-indigo-jsk-tools (2.2.5-0trusty-20170728-031458-0800) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.30.7-0ubuntu1.7) ...
Processing triggers for python-support (1.0.15) ...
W: Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_multiverse_binary-amd64_Packages.gz)
W: Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty-updates/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_binary-amd64_Packages.gz)
W: You may want to run apt-get update to correct these problems
Invoking 'apt-get clean'
 ---> 801917980842
Removing intermediate container 2d867893eea7
Step 27/29 : USER buildfarm
 ---> Running in 125dabe406f1
 ---> afd40ca35fc8
Removing intermediate container 125dabe406f1
Step 28/29 : ENTRYPOINT sh -c
 ---> Running in aad8007de771
 ---> 5f9441985877
Removing intermediate container aad8007de771
Step 29/29 : CMD PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH PATH=/usr/lib/ccache:$PATH python3 -u /tmp/ros_buildfarm/scripts/release/build_binarydeb.py indigo jsk_arc2017_baxter --sourcedeb-dir /tmp/binarydeb
 ---> Running in 7f6cca3cfbc8
 ---> 49496826227a
Removing intermediate container 7f6cca3cfbc8
Successfully built 49496826227a
Successfully tagged binarydeb_build.indigo_ubuntu_trusty_amd64_jsk_arc2017_baxter:latest
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Run Dockerfile - build binarydeb
# BEGIN SECTION: Run Dockerfile - build binarydeb
+ docker run --rm --cidfile=<http://build.ros.org/job/Ibin_uT64__jsk_arc2017_baxter__ubuntu_trusty_amd64__binary/ws/docker_build_binarydeb/docker.cid> -e=HOME= -e=TRAVIS= --net=host -v <http://build.ros.org/job/Ibin_uT64__jsk_arc2017_baxter__ubuntu_trusty_amd64__binary/ws/ros_buildfarm>:/tmp/ros_buildfarm:ro -v <http://build.ros.org/job/Ibin_uT64__jsk_arc2017_baxter__ubuntu_trusty_amd64__binary/ws/binarydeb>:/tmp/binarydeb -v /home/jenkins-agent/.ccache:/home/buildfarm/.ccache binarydeb_build.indigo_ubuntu_trusty_amd64_jsk_arc2017_baxter
# BEGIN SUBSECTION: build binarydeb
Package 'ros-indigo-jsk-arc2017-baxter' version: 4.1.4-0trusty-20171021-222328-0800
Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_multiverse_binary-amd64_Packages.gz)
Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty-updates/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_binary-amd64_Packages.gz)
You may want to run apt-get update to correct these problems
Invoking 'apt-src build ros-indigo-jsk-arc2017-baxter' in '/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4'
Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_multiverse_binary-amd64_Packages.gz)
Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty-updates/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_binary-amd64_Packages.gz)
You may want to run apt-get update to correct these problems
I: Building in /tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4 ..
dpkg-buildpackage: source package ros-indigo-jsk-arc2017-baxter
dpkg-buildpackage: source version 4.1.4-0trusty-20171021-222328-0800
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by Kentaro Wada <www.kentaro.wada@gmail.com>
 dpkg-source --before-build ros-indigo-jsk-arc2017-baxter-4.1.4
dpkg-buildpackage: host architecture amd64
dpkg-source: info: using options from ros-indigo-jsk-arc2017-baxter-4.1.4/debian/source/options: --auto-commit
 fakeroot debian/rules clean
dh  clean
   dh_testdir
   dh_auto_clean
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   dh_clean
Unknown option: buildsystem
dh_clean: warning: ignored unknown options in DH_OPTIONS
        rm -f debian/ros-indigo-jsk-arc2017-baxter.substvars
        rm -f debian/ros-indigo-jsk-arc2017-baxter.*.debhelper
        rm -rf debian/ros-indigo-jsk-arc2017-baxter/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
 debian/rules build
dh  build
   dh_testdir
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   debian/rules override_dh_auto_configure
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_configure -- \
                -DCATKIN_BUILD_BINARY_PACKAGE="1" \
                -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
                -DCMAKE_PREFIX_PATH="/opt/ros/indigo"
        mkdir -p obj-x86_64-linux-gnu
        cd obj-x86_64-linux-gnu
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Warning at CMakeLists.txt:9 (message):
  COULD NOT BE FOUND force_proximity_ros PACKAGE


-- Using CATKIN_DEVEL_PREFIX: /tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/obj-x86_64-linux-gnu/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/obj-x86_64-linux-gnu/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- Using these message generators: gencpp;geneus;genlisp;genpy
-- set EUSDIR to /opt/ros/indigo/share/euslisp/jskeus/eus
-- set ARCHDIR to Linux64
-- [roseus.cmake] loading roseus.cmake from jsk_arc2017_baxter
-- [roseus.cmake] roseus 1.6.3
-- [roseus.cmake] jskeus 1.1.0
-- [roseus.cmake] euslisp 9.23.0
-- [roseus.cmake] geneus 2.2.6
-- [roseus.cmake] genmsg 0.5.8
-- [roseus.cmake] message_generation Requires: gencpp;genlisp;genmsg;genpy
-- [roseus.cmake] generate all roseus messages
-- [roseus.cmake] jsk_arc2017_baxter depends on
-- [roseus.cmake] jsk_arc2017_baxter will compile
-- Generating .msg files for action jsk_arc2017_baxter/CalibJoint /tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/action/CalibJoint.action
Generating for action CalibJoint
-- jsk_arc2017_baxter: 8 messages, 3 services
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:411 (message):
  catkin_package() include dir
  '/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/obj-x86_64-linux-gnu/devel/include'
  should be placed in the devel space instead of the build space
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:100 (_catkin_package)
  CMakeLists.txt:64 (catkin_package)


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- checking for module 'collada-dom>=2.4.4'
--   found collada-dom, version 2.4.4
CMake Error at CMakeLists.txt:135 (find_package):
  By not providing "Findroslint.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "roslint", but
  CMake did not find one.

  Could not find a package configuration file provided by "roslint" with any
  of the following names:

    roslintConfig.cmake
    roslint-config.cmake

  Add the installation prefix of "roslint" to CMAKE_PREFIX_PATH or set
  "roslint_DIR" to a directory containing one of the above files.  If
  "roslint" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-jsk-arc2017-baxter-4.1.4'
make[1]: *** [override_dh_auto_configure] Error 2
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Building failed
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
    subprocess.check_call(cmd, cwd=source_dir)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-jsk-arc2017-baxter']' returned non-zero exit status 1
# END SUBSECTION

--------------------------------------------------------------------------------------------------
`apt-src build ros-indigo-jsk-arc2017-baxter` failed.
This is usually because of an error building the package.
The traceback from this failure (just above) is printed for completeness, but you can ignore it.
You should look above `E: Building failed` in the build log for the actual cause of the failure.
--------------------------------------------------------------------------------------------------

Build step 'Execute shell' marked build as failure
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 4486 killed;
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

**Comment by wkentaro** [comment]
https://github.com/ros/rosdistro/pull/16137
