### ISSUE TITLE
baxter.launch in jsk_arc2017_baxter does not work on baxter-c1

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2695]
Today, I faced the following errors in `roslaunch jsk_arc2017_baxter baxterlgv7.launch`:
- Critical one:
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/jsk_interactive_marker/scripts/transformable_markers_client.py", line 23, in <module>
    from jsk_recognition_utils.color import labelcolormap
  File "/home/pazeshun/ros/ws_jsk_apc/devel/lib/python2.7/dist-packages/jsk_recognition_utils/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 2, in <module>
  File "__init__.pxd", line 861, in init jsk_recognition_utils.color (/home/pazeshun/ros/ws_jsk_apc/build/jsk_recognition_utils/python/jsk_recognition_utils/color.c:4330)
ValueError: numpy.ufunc has the wrong size, try recompiling
...
[transformable_bin_markers-17] process has died [pid 5539, exit code 1, cmd /opt/ros/kinetic/share/jsk_interactive_marker/scripts/transformable_markers_client.py ~server:=transformable_interactive_server __name:=transformable_bin_markers __log:=/home/pazeshun/.ros/log/d3293bcc-759a-11e9-9cba-000af716d1cb/transformable_bin_markers-17.log].
log file: /home/pazeshun/.ros/log/d3293bcc-759a-11e9-9cba-000af716d1cb/transformable_bin_markers-17*.log
[transformable_cardboard_markers-18] process has died [pid 5545, exit code 1, cmd /opt/ros/kinetic/share/jsk_interactive_marker/scripts/transformable_markers_client.py ~server:=transformable_interactive_server __name:=transformable_cardboard_markers __log:=/home/pazeshun/.ros/log/d3293bcc-759a-11e9-9cba-000af716d1cb/transformable_cardboard_markers-18.log].
log file: /home/pazeshun/.ros/log/d3293bcc-759a-11e9-9cba-000af716d1cb/transformable_cardboard_markers-18*.log
```
- Others:
```
[ERROR] [1563173117.016683729] [/move_group:ros.moveit_ros_planning]: Exception while loading Hybrid: According to the loaded plugin descriptions the class Hybrid with base class type collision_detection::CollisionPlugin does not exist. Declared types are 
[ INFO] [1563176366.799618696] [/move_group:ros.moveit_ros_planning]: Using collision detector:FCL
```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 24, in run
    self.stream()
  File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 28, in stream
    self.formURL()
  File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 41, in formURL
    self.url += "&camera=%d" % self.axis.camera
TypeError: %d format: a number is required, not dict
```

I found the installed numpy is old (1.11.0). When I installed new numpy to the user install directory, ~~those errors were disappeared~~ the critical error was disappeared.
```
$ pip show numpy
Name: numpy
Version: 1.11.0
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires: 
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip install numpy --user --upgrade
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/1f/c7/198496417c9c2f6226616cff7dedf2115a4f4d0276613bab842ec8ac1e23/numpy-1.16.4-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 101kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.16.4
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ pip show numpy
Name: numpy
Version: 1.16.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/pazeshun/.local/lib/python2.7/site-packages
Requires: 
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

@knorth55 Do you have any ideas about baxter-c1's change?

**Comment by pazeshun** [comment]
> [ERROR] [1563173117.016683729] [/move_group:ros.moveit_ros_planning]: Exception while loading Hybrid: According to the loaded plugin descriptions the class Hybrid with base class type collision_detection::CollisionPlugin does not exist. Declared types are 
> [ INFO] [1563176366.799618696] [/move_group:ros.moveit_ros_planning]: Using collision detector:FCL

This error might be overlooked previously and may be able to be ignored. https://github.com/ros-planning/moveit/issues/1426

**Comment by pazeshun** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 24, in run
>     self.stream()
>   File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 28, in stream
>     self.formURL()
>   File "/opt/ros/kinetic/lib/axis_camera/axis.py", line 41, in formURL
>     self.url += "&camera=%d" % self.axis.camera
> TypeError: %d format: a number is required, not dict
> ```

This was my fault.
The cause of this error was that parameter `/camera` (type: dictionary) was set when I did `roslaunch openni2_launch openni2.launch`.
`axis.py` searches the parameter including `camera` for the camera number.
https://github.com/ros-drivers/axis_camera/blob/0.3.0/nodes/axis.py#L199-L204
Usually, this attempt fails and the default value `0` is used.
https://github.com/ros-drivers/axis_camera/blob/0.3.0/nodes/axis.py#L189
However, when `/camera` exists, this is hit and wrongly used.

**Comment by pazeshun** [comment]
system numpy is `python-numpy` `1:1.11.0-1ubuntu1` because current moveit can only be built with `numpy` `1.11.0`
see https://github.com/ros-planning/moveit/issues/1524#issuecomment-508879951.

please install higher `numpy` version (such as `1.16.4`) in your user local dir by `pip install --user numpy -U`.
