### ISSUE TITLE
Cannot import matplotlib.pyplot on kinetic and melodic travis tests

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2718]
https://github.com/start-jsk/jsk_apc/pull/2708#issuecomment-651225532
```
[instance_occlsegm:make] ERROR: Failure: ImportError (No module named _tkinter, please install the python-tk package)

[instance_occlsegm:make] ----------------------------------------------------------------------

[instance_occlsegm:make] Traceback (most recent call last):

[instance_occlsegm:make]   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName

[instance_occlsegm:make]     addr.filename, addr.module)

[instance_occlsegm:make]   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath

[instance_occlsegm:make]     return self.importFromDir(dir_path, fqname)

[instance_occlsegm:make]   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir

[instance_occlsegm:make]     mod = load_module(part_fqname, fh, filename, desc)

[instance_occlsegm:make]   File "/home/travis/ros/ws_jsk_apc/src/jsk_apc/demos/instance_occlsegm/ros/instance_occlsegm/tests/data_tests/test_download.py", line 5, in <module>

[instance_occlsegm:make]     import instance_occlsegm_lib

[instance_occlsegm:make]   File "/home/travis/ros/ws_jsk_apc/devel/.private/instance_occlsegm/lib/python2.7/dist-packages/instance_occlsegm_lib/__init__.py", line 35, in <module>

[instance_occlsegm:make]     exec(__fh.read())

[instance_occlsegm:make]   File "<string>", line 10, in <module>

[instance_occlsegm:make]   File "/home/travis/ros/ws_jsk_apc/src/jsk_apc/demos/instance_occlsegm/ros/instance_occlsegm/python/instance_occlsegm_lib/_io.py", line 7, in <module>

[instance_occlsegm:make]     import matplotlib.pyplot as plt

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>

[instance_occlsegm:make]     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup

[instance_occlsegm:make]     [backend_name], 0)

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>

[instance_occlsegm:make]     from . import tkagg  # Paint image to Tk photo blitter extension.

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>

[instance_occlsegm:make]     from six.moves import tkinter as Tk

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module

[instance_occlsegm:make]     mod = mod._resolve()

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve

[instance_occlsegm:make]     return _import_module(self.mod)

[instance_occlsegm:make]   File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module

[instance_occlsegm:make]     __import__(name)

[instance_occlsegm:make]   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>

[instance_occlsegm:make]     raise ImportError, str(msg) + ', please install the python-tk package'

[instance_occlsegm:make] ImportError: No module named _tkinter, please install the python-tk package
```

**Comment by pazeshun** [comment]
As the error message says, `python-tk` is not installed on `jskrobotics/jsk_apc:<kinetic/melodic>-latest-testing` docker image:
```
$ dpkg -l python-tk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
un  python-tk                   <none>             <none>             (no description available)
```
By contrast, `python-tk` is installed on `jskrobotics/jsk_apc:indigo-latest-testing` image:
```
# dpkg -l python-tk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  python-tk                   2.7.5-1ubuntu1     amd64              Tkinter - Writing Tk applications with Python
```

**Comment by pazeshun** [comment]
`python-tk` is dropped from `osrf/ros:<kinetic/melodic>-desktop-<xenial/bionic>`, which is original image of `jskrobotics/jsk_apc:<kinetic/melodic>-latest-testing`:
https://github.com/osrf/docker_images/issues/423

**Comment by pazeshun** [comment]
Dropping `python-tk` (and other "Recommends" dependencies) was what the maintainer expected: https://github.com/osrf/docker_images/issues/423#issuecomment-651638995
We have to install lacking dependencies explicitly -> #2719
